<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <!-- Comentariile XML alimentează documentația Swagger. -->
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MultiTenantSaaS.Application\MultiTenantSaaS.Application.csproj" />
    <ProjectReference Include="..\MultiTenantSaaS.Infrastructure\MultiTenantSaaS.Infrastructure.csproj" />
  </ItemGroup>

</Project>
